# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
  #vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  projectName: 'ChillMapWeb'
  # testProjectName: 'Tests'
  framework: netcoreapp2.2


steps:
- task: NodeTool@0
  inputs:
     checkLatest: true

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: publish
    arguments: '-c Release'    
    workingDirectory: 'ChillMap'
    publishWebProjects: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'ChillMap/ChillMapWeb/bin/Release/netcoreapp2.2/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure для учащихся (8638d1c1-9212-4735-8da1-982278043db5)'
    appType: 'webApp'
    WebAppName: 'chillhackmap'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'


# - task: DotNetCoreCLI@2
#   inputs:
#     command: test
#     projects: 'ChillMap/$(projectName)/$(testProjectName)/**/*.csproj'
#     arguments: '--configuration $(buildConfiguration)'
